### ISSUE TITLE
批量生成的时候，程序不能按照图片的命名排序？

### ISSUE THREAD

**Issue by baijunjie** [iwangx/sprite#1]
如题，期待您的改进：）

**Comment by iwangx** [comment]
不能按照图片名称排序，也不打算做这个功能。因为标准的图片命名方式不会用数字的

**Comment by baijunjie** [comment]
哦，需求是这样的，我要把一组序列图做成CSS3动画，所以需要按图片编号来生成雪碧图

**Comment by iwangx** [comment]
现在的最新版支持图片的拖拽，你把顺序自己调一下就是了

**Comment by baijunjie** [comment]
额，一套序列帧动画上百张图片，一个一个拖的话有蛋疼—_—！

**Comment by iwangx** [comment]
你是做游戏的吗？那么多图片

**Comment by baijunjie** [comment]
是一个微信中用的h5宣传页，有一个开场动画，视频渲染的，还挺炫，只有靠CSS3的序列图动画才能实现
